[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "binghello"
version = "0.0.1"
authors = []
description = ""
readme = "README.md"
requires-python = ">=3.7"
